import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Head, Link } from '@inertiajs/react';

export default function AdminPlans() {
  const [plans, setPlans] = useState([]), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [status, setStatus] = useState('');
  useEffect(() => { let cancelled = false; axios.get('/subscription-plans').then(response => !cancelled && setPlans(response.data?.plans || [])).catch(() => !cancelled && setStatus('Unable to load plans.')).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, []);
  const update = (id, key, value) => setPlans(current => current.map(plan => plan.id === id ? { ...plan, [key]: value } : plan));
  const save = async () => { setSaving(true); setStatus(''); try { const response = await axios.put('/admin/subscription-plans', { plans: plans.map(({ id, price, duration_days, description, is_featured, is_active }) => ({ id, price: price === '' ? null : price, duration_days, description, is_featured, is_active })) }); setPlans(response.data.plans); setStatus('Subscription pricing saved successfully.'); } catch (error) { setStatus(error.response?.data?.message || 'Unable to save plans.'); } finally { setSaving(false); } };
  return <><Head title="Subscription pricing"/><div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-xl font-bold">Subscription pricing</h1><p className="mt-1 text-sm text-[#787b86]">Control the server-priced one-time plans shown at PayMongo checkout.</p></div><div className="flex gap-2"><Link href="/admin/subscriptions" className="flex h-10 items-center rounded-lg border border-[#2a2e39] px-4 text-sm font-semibold">Transactions</Link><button onClick={save} disabled={saving || loading} className="h-10 rounded-lg bg-[#2962ff] px-4 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save pricing'}</button></div></div><div className="grid gap-4 lg:grid-cols-3">{plans.map(plan => <article key={plan.id} className="rounded-xl border border-[#2a2e39] bg-[#131722] p-5 text-white"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-wider text-[#5b8cff]">{plan.code}</div><h2 className="mt-1 text-lg font-bold">{plan.name}</h2></div><label className="flex items-center gap-2 text-xs text-[#b2b5be]"><input type="checkbox" checked={plan.is_active} onChange={event => update(plan.id, 'is_active', event.target.checked)}/>Active</label></div><div className="mt-5 grid gap-4"><Field label="Price (PHP)"><input type="number" min="0.01" step="0.01" value={plan.price ?? ''} onChange={event => update(plan.id, 'price', event.target.value)} placeholder="Set a price"/></Field><Field label="Replay access days"><input type="number" min="1" max="3650" value={plan.duration_days} onChange={event => update(plan.id, 'duration_days', Number(event.target.value))}/></Field><Field label="Plan description"><input maxLength="160" value={plan.description ?? ''} onChange={event => update(plan.id, 'description', event.target.value)}/></Field><label className="flex items-center gap-2 text-xs text-[#b2b5be]"><input type="checkbox" checked={plan.is_featured} onChange={event => update(plan.id, 'is_featured', event.target.checked)}/>Highlight as popular</label></div></article>)}</div>{loading && <div className="py-8 text-center text-[#787b86]">Loading plan settings…</div>}{status && <div className="rounded-lg border border-[#2a2e39] bg-[#131722] p-3 text-sm text-blue-300">{status}</div>}</div></>;
}

function Field({ label, children }) { return <label className="grid gap-1.5 text-xs font-semibold text-[#787b86]">{label}{React.cloneElement(children, { className: 'h-10 rounded-lg border border-[#2a2e39] bg-[#0b0e14] px-3 text-sm text-white outline-none focus:border-[#2962ff]' })}</label>; }
