import React, { useEffect, useState } from 'react';
import { Head } from '@inertiajs/react';
import axios from 'axios';
import { QrCode, Save } from 'lucide-react';
import { useTheme } from '../../Context/ThemeContext';

export default function AdminPaymentSettings() {
  const {theme}=useTheme(), dark=theme==='bg-skin-black';
  const [form,setForm]=useState({account_number:'',account_name:'',rules:''}), [qrUrl,setQrUrl]=useState(null), [qr,setQr]=useState(null), [removeQr,setRemoveQr]=useState(false), [saving,setSaving]=useState(false), [status,setStatus]=useState('');
  useEffect(()=>{axios.get('/payment-settings').then(r=>{const s=r.data?.settings??{};setForm({account_number:s.account_number??'',account_name:s.account_name??'',rules:s.rules??''});setQrUrl(s.qr_code_url??null);});},[]);
  const save=async(e)=>{e.preventDefault();setSaving(true);setStatus('');const data=new FormData();Object.entries(form).forEach(([k,v])=>data.append(k,v));if(qr)data.append('qr_code',qr);if(removeQr)data.append('remove_qr_code','1');try{const r=await axios.post('/admin/payment-settings',data);setStatus(r.data?.message??'Saved.');if(qr)setQrUrl(URL.createObjectURL(qr));if(removeQr)setQrUrl(null);setQr(null);setRemoveQr(false);}catch(err){setStatus(err.response?.data?.message??Object.values(err.response?.data?.errors??{}).flat()[0]??'Unable to save.');}finally{setSaving(false);}};
  const field=`rounded-lg border px-3 py-2 text-sm outline-none focus:border-[#2962ff] ${dark?'border-[#2a2e39] bg-[#0b0e14] text-white':'border-slate-300 bg-white text-slate-900'}`;
  return <><Head title="Payment settings"/><form onSubmit={save} className={`mx-auto max-w-3xl rounded-xl border p-5 ${dark?'border-[#2a2e39] bg-[#131722] text-white':'border-slate-200 bg-white text-slate-900'}`}><div className="flex items-center justify-between"><div><h1 className="text-xl font-bold">GCash payment settings</h1><p className="mt-1 text-sm text-[#787b86]">Details displayed during subscription checkout.</p></div><button disabled={saving} className="flex h-10 items-center gap-2 rounded-lg bg-[#2962ff] px-4 text-sm font-bold text-white disabled:opacity-50"><Save size={15}/>{saving?'Saving…':'Save'}</button></div><div className="mt-6 grid gap-4"><label className="grid gap-1.5 text-xs font-semibold">Account number<input required value={form.account_number} onChange={e=>setForm({...form,account_number:e.target.value})} className={field}/></label><label className="grid gap-1.5 text-xs font-semibold">Account name<input required value={form.account_name} onChange={e=>setForm({...form,account_name:e.target.value})} className={field}/></label><label className="grid gap-1.5 text-xs font-semibold">Payment rules<textarea rows="6" value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})} className={field} placeholder="Enter one rule per line"/></label><label className="grid gap-1.5 text-xs font-semibold">GCash QR code<input type="file" accept="image/*" onChange={e=>{setQr(e.target.files?.[0]??null);setRemoveQr(false)}} className={field}/></label>{(qr||qrUrl)&&<div className="flex items-start gap-4"><div className="flex h-40 w-40 items-center justify-center overflow-hidden rounded-lg border border-slate-300 bg-white">{qr||qrUrl?<img src={qr?URL.createObjectURL(qr):qrUrl} className="h-full w-full object-contain"/>:<QrCode/>}</div><button type="button" onClick={()=>{setQr(null);setQrUrl(null);setRemoveQr(true)}} className="text-xs font-semibold text-red-500">Remove QR code</button></div>}{status&&<div className="rounded-lg bg-blue-500/10 p-3 text-sm text-blue-500">{status}</div>}</div></form></>;
}
