import React, { useEffect, useState } from 'react';
import { Head } from '@inertiajs/react';
import axios from 'axios';
import { Inbox, Save, Search } from 'lucide-react';
import { useTheme } from '../../Context/ThemeContext';

const statuses = ['submitted','reviewing','planned','in_progress','completed','declined'];
const priorities = ['low','normal','high','urgent'];
const categories = ['payment','subscription','account','enhancement','feature','bug','usability','performance','other'];

export default function AdminFeedbackIndex() {
    const { theme } = useTheme(); const isDark = theme === 'bg-skin-black';
    const [items,setItems]=useState([]); const [selected,setSelected]=useState(null); const [filters,setFilters]=useState({search:'',status:'',category:'',priority:''}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
    const load=async()=>{setLoading(true);setError('');try{const {data}=await axios.get('/admin/feedback/items',{params:filters});setItems(data.feedback??[]);setSelected((current)=>(data.feedback??[]).find((item)=>item.id===current?.id)??data.feedback?.[0]??null);}catch(e){setError(e.response?.data?.message||'Unable to load feedback.');}finally{setLoading(false);}};
    useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[filters.search,filters.status,filters.category,filters.priority]);
    const update=async()=>{if(!selected)return;setSaving(true);setError('');try{const {data}=await axios.put(`/admin/feedback/items/${selected.id}`,{status:selected.status,priority:selected.priority,admin_response:selected.adminResponse});setSelected(data.feedback);setItems((current)=>current.map((item)=>item.id===data.feedback.id?data.feedback:item));}catch(e){setError(e.response?.data?.message||'Unable to update feedback.');}finally{setSaving(false);}};
    const panel=isDark?'border-[#2a2e39] bg-[#131722]':'border-slate-200 bg-white'; const field=isDark?'border-[#2a2e39] bg-[#0b0e14] text-white':'border-slate-200 bg-slate-50';
    return <><Head title="Customer Support"/><div className={`space-y-4 ${isDark ? 'text-[#d1d4dc]' : 'text-slate-900'}`}><div><div className="text-xs font-bold uppercase tracking-[.18em] text-[#2962ff]">Customer operations</div><h1 className={`mt-1 text-2xl font-bold ${isDark?'text-white':'text-slate-900'}`}>Customer support inbox</h1><p className="mt-1 text-sm text-[#787b86]">Resolve payment, subscription, account, and product requests.</p></div>
    <div className={`grid gap-2 rounded-xl border p-3 sm:grid-cols-4 ${panel}`}><label className={`flex h-10 items-center gap-2 rounded-lg border px-3 ${field}`}><Search size={14}/><input value={filters.search} onChange={(e)=>setFilters((c)=>({...c,search:e.target.value}))} placeholder="Search feedback or user" className="min-w-0 flex-1 bg-transparent text-xs outline-none"/></label>{[['status',statuses],['category',categories],['priority',priorities]].map(([key,options])=><select key={key} value={filters[key]} onChange={(e)=>setFilters((c)=>({...c,[key]:e.target.value}))} className={`h-10 rounded-lg border px-3 text-xs capitalize outline-none ${field}`}><option value="">All {key}</option>{options.map((value)=><option key={value} value={value}>{value.replace('_',' ')}</option>)}</select>)}</div>
    {error&&<div className="rounded-lg bg-red-500/10 px-3 py-2 text-xs text-red-400">{error}</div>}<div className="grid min-h-[600px] gap-4 lg:grid-cols-[.9fr_1.1fr]"><section className={`overflow-hidden rounded-xl border ${panel}`}><div className="flex items-center justify-between border-b border-[#2a2e39] p-4"><div className="flex items-center gap-2 text-sm font-bold"><Inbox size={16}/>Inbox</div><span className="text-[10px] text-[#787b86]">{items.length} items</span></div><div className="max-h-[650px] overflow-y-auto">{loading?<p className="p-5 text-xs text-[#787b86]">Loading…</p>:!items.length?<p className="p-12 text-center text-xs text-[#787b86]">No feedback matches these filters.</p>:items.map((item)=><button key={item.id} onClick={()=>setSelected(item)} className={`block w-full border-b p-4 text-left ${isDark?'border-[#2a2e39]':'border-slate-200'} ${selected?.id===item.id?'bg-[#2962ff]/10':'hover:bg-[#2962ff]/5'}`}><div className="flex gap-2"><span className="min-w-0 flex-1 truncate text-xs font-bold">{item.title}</span><span className={`text-[9px] font-bold uppercase ${item.priority==='urgent'?'text-red-400':item.priority==='high'?'text-amber-400':'text-[#787b86]'}`}>{item.priority}</span></div><div className="mt-1 truncate text-[10px] text-[#787b86]">{item.user?.name} · {item.category} · {item.status.replace('_',' ')}</div><p className="mt-2 line-clamp-2 text-xs leading-5 text-[#787b86]">{item.description}</p></button>)}</div></section>
    <section className={`rounded-xl border p-5 ${panel}`}>{!selected?<div className="flex h-full items-center justify-center text-xs text-[#787b86]">Select feedback to review.</div>:<div><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-wider text-[#5b8cff]">{selected.category}</div><h2 className="mt-1 text-xl font-bold">{selected.title}</h2><div className="mt-1 text-xs text-[#787b86]">{selected.user?.name} · {selected.user?.email} · {new Date(selected.createdAt).toLocaleString()}</div></div></div><div className={`mt-5 rounded-lg border p-4 text-sm leading-6 ${field}`}>{selected.description}</div>{selected.pageUrl&&<a href={selected.pageUrl} target="_blank" rel="noreferrer" className="mt-2 block truncate text-xs text-[#2962ff]">Context: {selected.pageUrl}</a>}<div className="mt-6 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Status<select value={selected.status} onChange={(e)=>setSelected((c)=>({...c,status:e.target.value}))} className={`mt-1.5 h-10 w-full rounded-lg border px-3 text-xs capitalize ${field}`}>{statuses.map((value)=><option key={value} value={value}>{value.replace('_',' ')}</option>)}</select></label><label className="text-xs font-semibold">Priority<select value={selected.priority} onChange={(e)=>setSelected((c)=>({...c,priority:e.target.value}))} className={`mt-1.5 h-10 w-full rounded-lg border px-3 text-xs capitalize ${field}`}>{priorities.map((value)=><option key={value} value={value}>{value}</option>)}</select></label></div><label className="mt-4 block text-xs font-semibold">Response to user<textarea rows="7" value={selected.adminResponse??''} onChange={(e)=>setSelected((c)=>({...c,adminResponse:e.target.value}))} className={`mt-1.5 w-full rounded-lg border p-3 text-sm leading-6 outline-none focus:border-[#2962ff] ${field}`} placeholder="Share the decision, progress, workaround, or completion note…"/></label><button onClick={update} disabled={saving} className="mt-4 flex h-10 items-center gap-2 rounded-lg bg-[#2962ff] px-4 text-xs font-bold text-white disabled:opacity-50"><Save size={14}/>{saving?'Saving…':'Save update'}</button></div>}</section></div></div></>;
}
