import React, { useEffect, useState } from 'react';
import { Link, router, usePage } from '@inertiajs/react';
import axios from 'axios';
import { AlertTriangle, Bell, CreditCard, LayoutDashboard, LogOut, Menu, MessageSquareText, Moon, Settings, ShieldCheck, Sun, Users, X } from 'lucide-react';
import getAppLogo from '../../Components/SystemSettings/ApplicationLogo';
import { useSidebar } from '../../Context/SidebarContext';
import { useTheme } from '../../Context/ThemeContext';

export default function AdminNavbar() {
    const { auth } = usePage().props;
    const { toggleSidebar } = useSidebar();
    const { theme, setTheme } = useTheme();
    const isDark = theme === 'bg-skin-black';
    const [logo, setLogo] = useState('');
    const [showLogoutModal, setShowLogoutModal] = useState(false);
    const [showModuleMenu, setShowModuleMenu] = useState(false);

    useEffect(() => { getAppLogo().then(setLogo); }, []);
    const toggleTheme = () => {
        const nextTheme = isDark ? 'bg-skin-white' : 'bg-skin-black';
        setTheme(nextTheme);
        axios.post('/update-theme', { theme: nextTheme.replace('bg-', '') }).catch(() => {});
    };
    const logout = () => { setShowLogoutModal(false); router.post('/logout'); };
    const navLink = `flex h-8 items-center gap-2 rounded-md px-3 text-xs font-semibold transition ${isDark ? 'text-[#b2b5be] hover:bg-[#2a2e39] hover:text-white' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'}`;

    return <header className={`flex h-14 items-center border-b px-3 sm:px-4 ${isDark ? 'border-[#2a2e39] bg-[#131722] text-[#d1d4dc]' : 'border-slate-200 bg-white text-slate-800'}`}>
        <button type="button" onClick={()=>toggleSidebar()} className={`mr-2 flex h-9 w-9 shrink-0 items-center justify-center rounded-md ${isDark?'text-[#b2b5be] hover:bg-[#2a2e39] hover:text-white':'text-slate-600 hover:bg-slate-100 hover:text-slate-900'}`} aria-label="Toggle admin sidebar" title="Toggle sidebar"><Menu size={20}/></button>
        <Link href="/dashboard" className="flex shrink-0 items-center gap-2 pr-4"><span className="flex h-8 w-8 items-center justify-center overflow-hidden rounded-md bg-[#2962ff]">{logo?<img src={logo} alt="BacktradeLab" className="h-full w-full object-contain p-1"/>:<ShieldCheck size={17} className="text-white"/>}</span><span className="hidden sm:block"><span className="block text-sm font-bold leading-none">BacktradeLab</span><span className="mt-1 block text-[9px] font-semibold uppercase tracking-[.2em] text-[#787b86]">Admin console</span></span></Link>
        <nav className="hidden items-center gap-1 lg:flex"><Link href="/dashboard" className={navLink}><LayoutDashboard size={14}/>Overview</Link><Link href="/users" className={navLink}><Users size={14}/>Users</Link><Link href="/admin/feedback" className={navLink}><MessageSquareText size={14}/>Customer support</Link><Link href="/admin/subscriptions" className={navLink}><CreditCard size={14}/>Payments</Link><Link href="/admin/subscription-plans" className={navLink}><CreditCard size={14}/>Pricing</Link><Link href="/settings" className={navLink}><Settings size={14}/>Settings</Link></nav>
        <button type="button" onClick={()=>setShowModuleMenu((visible)=>!visible)} className={`ml-auto flex h-9 w-9 shrink-0 items-center justify-center rounded-md border lg:hidden ${isDark?'border-[#434955] bg-[#2a2e39] text-white':'border-slate-300 bg-slate-100 text-slate-900'}`} aria-label={showModuleMenu ? 'Close admin module menu' : 'Open admin module menu'} aria-expanded={showModuleMenu}><Menu size={20}/></button>
        {showModuleMenu && <><button type="button" className="fixed inset-0 top-14 z-[190] bg-black/40 lg:hidden" onClick={()=>setShowModuleMenu(false)} aria-label="Close module menu"/><nav className={`fixed inset-x-2 top-16 z-[220] grid max-h-[calc(100dvh-5rem)] gap-1 overflow-y-auto rounded-xl border p-3 shadow-2xl sm:left-auto sm:right-3 sm:w-80 lg:hidden ${isDark?'border-[#2a2e39] bg-[#131722]':'border-slate-200 bg-white'}`} aria-label="Admin modules">{[["/dashboard",LayoutDashboard,"Overview"],["/users",Users,"Users"],["/admin/feedback",MessageSquareText,"Customer support"],["/admin/subscriptions",CreditCard,"Payments"],["/admin/subscription-plans",CreditCard,"Pricing"],["/settings",Settings,"Settings"]].map(([href,Icon,label])=><Link key={href} href={href} onClick={()=>setShowModuleMenu(false)} className={`${navLink} h-11 text-sm`}><Icon size={17}/>{label}</Link>)}</nav></>}
        <div className={`ml-0 flex shrink-0 items-center gap-0.5 border-l pl-1 sm:gap-1 sm:pl-2 lg:ml-auto ${isDark?'border-[#2a2e39]':'border-slate-200'}`}><Link href="/notifications/view-all-notifications" className="relative rounded-md p-2 text-[#787b86] hover:bg-white/10" aria-label="Notifications"><Bell size={16}/>{Number(auth?.unread_notifications)>0&&<span className="absolute right-1 top-1 h-1.5 w-1.5 rounded-full bg-red-500"/>}</Link><button type="button" onClick={toggleTheme} className="rounded-md p-2 text-[#787b86] hover:bg-white/10" aria-label="Toggle theme">{isDark?<Sun size={16}/>:<Moon size={16}/>}</button><Link href="/profile" className="hidden rounded-md px-2 py-1.5 text-right hover:bg-white/5 sm:block"><span className="block max-w-32 truncate text-xs font-semibold">{auth?.user?.name}</span><span className="block text-[9px] uppercase tracking-wider text-[#787b86]">Superadmin</span></Link><button type="button" onClick={()=>setShowLogoutModal(true)} className="rounded-md p-2 text-[#787b86] hover:bg-red-500/10 hover:text-red-400" aria-label="Sign out"><LogOut size={16}/></button></div>
        {showLogoutModal&&<div className="fixed inset-0 z-[220] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onMouseDown={(event)=>event.target===event.currentTarget&&setShowLogoutModal(false)}><div className={`w-full max-w-sm overflow-hidden rounded-xl border shadow-2xl ${isDark?'border-[#2a2e39] bg-[#131722] text-[#d1d4dc]':'border-slate-200 bg-white text-slate-900'}`} role="dialog" aria-modal="true" aria-labelledby="admin-logout-title"><div className={`flex items-center justify-between border-b px-5 py-4 ${isDark?'border-[#2a2e39]':'border-slate-200'}`}><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-500/10 text-amber-400"><AlertTriangle size={18}/></span><div><h2 id="admin-logout-title" className="text-sm font-bold">Sign out of admin console?</h2><p className="mt-0.5 text-[11px] text-[#787b86]">Your administrative session will end.</p></div></div><button type="button" onClick={()=>setShowLogoutModal(false)} className="rounded-md p-1.5 text-[#787b86] hover:bg-white/10" aria-label="Close"><X size={17}/></button></div><div className="px-5 py-4 text-xs leading-5 text-[#787b86]">You will need to authenticate again before managing users, feedback, settings, or system access.</div><div className={`flex justify-end gap-2 border-t px-5 py-4 ${isDark?'border-[#2a2e39]':'border-slate-200'}`}><button type="button" onClick={()=>setShowLogoutModal(false)} className={`h-9 rounded-md border px-4 text-xs font-semibold ${isDark?'border-[#2a2e39] hover:bg-white/5':'border-slate-200 hover:bg-slate-50'}`}>Stay signed in</button><button type="button" onClick={logout} className="flex h-9 items-center gap-2 rounded-md bg-red-500 px-4 text-xs font-bold text-white hover:bg-red-600"><LogOut size={14}/>Sign out</button></div></div></div>}
    </header>;
}
